name = "memo-feeds"
main = "src/index.tsx"
compatibility_date = "2024-08-06"
keep_vars = true

[vars]
EXPIRE_DAYS = "7"
# CORS_ORIGIN = "https://example.com"
# TG_BOT_TOKEN = "123456789:abcdefghijklmnopqrstuvwxyzABCDEFGHI"
# TG_USER_ID = "123456789"

[[kv_namespaces]]
binding = "MEMOS"
id = "ec108d488ca4440fb47035ba1f1e8fc3"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
